### PR TITLE
Update cuke modeler dependency

### PR DESCRIPTION
**Pull request by cartoloupe**
addresses https://github.com/grange-insurance/cuke_slicer/issues/4

There were two tests failing for me when running the tests locally; but, these tests also failed on the latest master branch, so no new failures observed.

Also, not sure how, but the previous commit also got included here; apologies for the diff confusion.

### CODE REVIEW

**Comment by cartoloupe** [comment]
@ashtony42 are the next steps to: 

1. bump `lib/cuke_slicer/version.rb` to 2.1.0 (or 3.0.0) in master
2. release the new version of the gem?

**Comment by ashtony42** [comment]
Will probably use 2.1.0, but we have permission things to resolve first.

Currently, the only owner of the cuke_slicer gem on rubygems.org is enkessler. 

In the short term, if he's willing to handle the version update, that would work, but we'll need some people who are members of the grange_insurance github to have permissions to cuke_slicer on rubygems.

**Comment by enkessler** [comment]
@ashtony42 I can push out the new version, sure. Also, I'll look into what it takes to add additional owners to a gem on RubyGems.

Regarding the version number: because the new version of cuke_slicer will no longer be compatible with cuke-modeler 0.x, there is some [debate ](https://github.com/mojombo/semver/issues/148) over whether this is a breaking change or not (and thus require a 3.0 release of cuke_slicer).

If there is only the one spot in the code that needs updating, we could simply add a quick conditional so that `#rows` or `#row_elements` is called as needed and if we did that then it wouldn't matter which version of cuke_modeler people were using and the cuke_slicer version could be left at 2.0.1 or 2.1.0 (depending on whether or not you consider adding support for a newer version of a dependency to be adding functionality).

**Comment by enkessler** [comment]
@ashtony42 Your thoughts?

**Comment by enkessler** [comment]
@ashtony42 @dbwest It looks like all that I need to add new owners to gems is an email address for them. Whose email should I use? I'm only seeing one person in the grange-insurance organization. Is there someone in charge?

**Comment by dbwest** [comment]
@enkessler Do you know whose name to use? @ashtony42, is it ok if he adds your name to the project on Rubygems? I think it's important to have you on there b/c you are an admin for Grange. I agree that we should bump the breaking change version to 3.0 and have the non-breaking change bump to 2.0.1 (support for a newer version of the dependency does not add any functionality AFAIK.)

Who will volunteer to make those pull requests or updates?

**Comment by enkessler** [comment]
@dbwest @ashtony42 I can go ahead and do the updates needed to make it work with both major versions of cuke_modeler. Adding Aston as an owner sounds good too. @ashtony42 should I use your GitHub email or your Grange email (and what is your Grange email, if so)?

**Comment by enkessler** [comment]
#6 has everything working again. It should just need a version number bump and a history file update before it's good to release again.

**Comment by ashtony42** [comment]
the two current owners of the grange github should be good for rubygems.
I asked which email Flatt wanted to use, and thus:
 jonathanm.flatt@gmail.com
and this one for me
a_freidenberger@hotmail.com

**Comment by enkessler** [comment]
@jmflatt @ashtony42 I've added Ashton as an owner but Jon's email does not appear to be valid. Still, now that at least one of you is an owner, you guys should have everything that you need for the rest of the release process.

**Pull request merged**
